# Generated by Django 3.2.9 on 2021-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='default name', max_length=100),
        ),
    ]
