# Generated by Django 3.2.9 on 2021-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0002_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='end_till',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='start_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
