# Generated by Django 3.2.9 on 2021-12-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0003_auto_20211203_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='end_till',
            field=models.DateTimeField(blank=True, default='default name', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='start_at',
            field=models.DateTimeField(blank=True, default='default name', null=True),
        ),
    ]
